// Generates docs/modes.md and docs/shortcuts.md from the registries, so the
// documentation can never drift from what the app actually offers.
// Run after `npm run build`: node scripts/gen-docs.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { MODES, CATEGORIES } = await import(path.join(root, 'dist/src/modes/index.js'));
const { buildShortcuts } = await import(path.join(root, 'dist/src/shortcuts.js'));

const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const control = (c) => {
  if (c.kind === 'select') return `**${c.label}**: ${c.options.map((o) => `\`${o.value}\``).join(' / ')} (default \`${c.default}\`)`;
  if (c.kind === 'toggle') return `**${c.label}** (${c.default ? 'on' : 'off'} by default)`;
  return `**${c.label}**: free text${c.default ? ` (default \`${c.default}\`)` : ''}`;
};

let md = `# Tool modes\n\n> Generated by \`scripts/gen-docs.mjs\` from \`src/modes/index.ts\` — do not edit by hand.\n\n`;
md += `c64 ships **${MODES.length} tools** in ${CATEGORIES.length} categories. Every tool is a pure function that runs in your browser (in a Web Worker above 150 000 characters); none of them makes a network request.\n\n`;
md += `Pretty / Raw is the switch in every pane's option bar: *Pretty* is the formatted or structured result, *Raw* the minified or literal one. Tools marked "—" produce a single output.\n\n`;
for (const cat of CATEGORIES) {
  const tools = MODES.filter((m) => m.category === cat);
  if (!tools.length) continue;
  md += `## ${cat}\n\n| Tool | What it does | Pretty / Raw | Options |\n|---|---|---|---|\n`;
  for (const m of tools) {
    const opts = m.controls.length ? m.controls.map(control).join('<br>') : '—';
    md += `| **${esc(m.label)}** <br><sub>\`${m.id}\`</sub> | ${esc(m.description)} | ${m.supportsPretty ? 'yes' : '—'} | ${opts} |\n`;
  }
  md += '\n';
}
md += `## Rich views\n\nSome tools return a structured view instead of plain text (the **Copy** and **Download** buttons still use the text form): JSON Tree / Path (collapsible tree, path bar, live queries), JSON Graph (zoomable card tree), CSV (table), JWT (decoded segments and claims), URL (breakdown + query parameters), Case Converter (every variant at once), Hash (digest table), Number Base (per-base table), Unix Time (date cards), UUID (decoded ids), Text Diff (side-by-side / inline), JSON / XML / YAML Compare (aligned trees with filters and navigation), List Compare (set tiles), Schema Validate (error table), Regex (highlighted matches + groups), Markdown (sanitised preview), Text Statistics (tiles), Cron (description + next runs), Color (swatches, scale, contrast), QR Code (rendered SVG), TOTP (live code and countdown), Unit Converter, IP / Subnet and chmod (cards) and Data URL (file preview).\n`;
fs.writeFileSync(path.join(root, 'docs/modes.md'), md);

const shortcuts = buildShortcuts({ openPalette() {}, toggleHelp() {}, focusSearch() {} });
let sc = `# Keyboard shortcuts\n\n> Generated by \`scripts/gen-docs.mjs\` from \`src/shortcuts.ts\` — do not edit by hand.\n\nShortcuts use **Alt+Shift+key** so they never collide with text selection inside the editor or with browser tab shortcuts (the command palette is ⌘/Ctrl+K because that is what everyone expects). Matching is on the physical key, so macOS Option-key symbols never leak into the editor.\n\n`;
for (const g of ['Panes', 'Editing', 'Workspace']) {
  sc += `## ${g}\n\n| Keys | Action |\n|---|---|\n`;
  for (const s of shortcuts.filter((s) => s.group === g)) sc += `| \`${s.keys.replace('⌘', 'Cmd')}\` | ${esc(s.label)} |\n`;
  sc += '\n';
}
sc += `## Inside a pane\n\n| Keys | Action |\n|---|---|\n| \`Tab\` to a seam, then arrows | Resize (Shift = bigger steps); double-click a seam to reset / even out |\n| \`↑ ↓ ← →\`, \`Enter\`, \`c\`, \`p\` | In a tree: move, expand/collapse, select, copy value, copy path |\n| \`+ − 0\`, arrows | In a graph: zoom, fit, pan |\n| Double-click the pane name | Rename the pane |\n| \`Tab\` in the editor | Inserts a tab character |\n`;
fs.writeFileSync(path.join(root, 'docs/shortcuts.md'), sc);
console.log(`docs/modes.md (${MODES.length} modes), docs/shortcuts.md (${shortcuts.length} shortcuts)`);
