// Copies package.json's version into src/version.ts and public/sw.js so the
// UI, the service-worker cache name and the release tag can never disagree.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

const write = (rel, content) => {
  const abs = path.join(root, rel);
  if (fs.existsSync(abs) && fs.readFileSync(abs, 'utf8') === content) return;
  fs.writeFileSync(abs, content);
  console.log(`version ${version} → ${rel}`);
};

write('src/version.ts', `// Generated by scripts/sync-version.mjs from package.json — do not edit by hand.\nexport const VERSION = '${version}';\n`);

const sw = path.join(root, 'public/sw.js');
if (fs.existsSync(sw)) {
  const src = fs.readFileSync(sw, 'utf8').replace(/const VERSION = '[^']*';/, `const VERSION = '${version}';`);
  write('public/sw.js', src);
}
